version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  run-build-and-deploy:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build and Deploy
          command: yarn build
    filters:
      branches:
        only: main
  runt-test:
    docker:
      - image: cimg/node:16.14.2
      steps:
        - run:
            name: Install Dependencies
            command: yarn
        - run:
            name: Run Tests
            command: yarn test
      filters:
        branches:
          only: /.*/
          ignore: main
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
  run-approval-test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    filters:
      branches:
        only: main
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Approval Tests
          command: yarn approval-test
          
workflows:
  run-build-and-deploy:
    jobs:
      - run-approval-test:
          type: approval
      - runt-test:
          requires:
            - run-approval-test
      - run-build-and-deploy:
          requires:
            - runt-test
          filters:
            branches:
              only: main
