version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build and Deploy
          command: yarn build && yarn deploy

  test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test

workflows:
  build-and-deploy-after-test:
    jobs:
      - run-approval-test:
          type: approval
          requires:
            - test
      - test:
          requires:
            - run-approval-test
          filters:
            branches:
              only: main
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: main
