version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  run-build-and-deploy:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build and Deploy
          command: yarn build
  run-test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
    filters:
      branches:
        ignore: main

workflows:
  run-build-and-deploy:
    jobs:
      - run-approval-test:
          type: approval
      - run-test:
          requires:
            - run-approval-test
          filters:
            branches:
              only: /.*/
      - run-build-and-deploy:
          requires:
            - run-test
          filters:
            branches:
              only: /.*/
