version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  run-build-and-deploy:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build
          command: yarn build
  run-test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
    filters:
      branches:
        ignore: main
  deploy-to-heroku:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: heroku/deploy
    filters:
      branches:
        only: main

workflows:
  run-build-and-deploy:
    jobs:
      - run-approval-test:
          type: approval
          filters:
            branches:
              ignore: main
      - run-test:
          requires:
            - run-approval-test
          filters:
            branches:
              only: /.*/
      - run-build-and-deploy:
          requires:
            - run-test
          filters:
            branches:
              only: /.*/
      - deploy-to-heroku:
          requires:
            - run-build-and-deploy
          filters:
            branches:
              only: main
