version: 2.1

jobs:
  run-test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test

  run-build-test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test

  build-and-deploy:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build

  run-approval-test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Approval Tests
          command: yarn approval-test

  merge-coverage-report:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Approval Tests
          command: yarn test --coverage

workflows:
  run-build-and-test:
    jobs:
      - run-approval-test:
          type: approval
          filters:
            branches:
              only:
                - main
      - run-test:
          requires:
            - run-approval-test
          filters:
            branches:
              only:
                - main
      - merge-coverage-report:
          requires:
            - run-test

  run-build-and-deploy:
    jobs:
      - run-build-test:
          filters:
            branches:
              only:
                - prod
      - build-and-deploy:
          requires:
            - run-build-test
          filters:
            branches:
              only:
                - prod
